name: Outdated Dependency Check

on:
  # This can be used to automatically check for outdated dependencies once a month
  schedule:
    - cron: "0 5 1 * *" # run at midnight UTC
  # This can be used to allow manually triggering dependency checks from the web interface
  workflow_dispatch:

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    name: Outdated Dependency Check

    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven
      - name: Check for outdated dependencies
        run: ./mvnw com.giovds:outdated-maven-plugin:check
